posts/urls.py
from django.urls import path
from posts.views import (PostsFeedView, CreatePostView, PostDetailView)

urlpatterns = [
    path(
        route='new', 
        view=CreatePostView.as_view(),
        name='create_post'
    ),
    path(
        route='posts', 
        view=PostsFeedView.as_view(),
        name='feed'
    ),
    
]

"""path(
    route='<str:post_id>',
    view=PostDetailView.as_view(),
    name='post_detail'
),"""

red/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include(('posts.urls', 'posts'),  namespace='posts')),

    path('users/', include(('users.urls', 'users'), namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

users/urls.py
from django.urls import path
from users.views import (LoginView, LogoutView,
    UpdateProfileView, UserDetailView,
    SignupView)


urlpatterns = [
    path(
        route='login',
        view=LoginView.as_view(),
        name='login'
    ),
    path(
        route='logout',
        view=LogoutView.as_view(),
        name='logout'
    ),
    path(
        route='signup',
        view=SignupView.as_view(),
        name='signup'
    ),
    path(
        route='mw/update',
        view=UpdateProfileView.as_view(),
        name='user_update'
    ),
    path(
        route='profile/<str:username>',
        view=UserDetailView.as_view(),
        name='detail'
    ),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}

    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css"integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt"crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
</head>
<body>
    {% include "nav.html" %}
    
    <div class="container mt-5">
        {% block container %}
        {% endblock %}
    </div>
</body>
</html>

templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg fixed-top" id="main-navbar">
    <div class="container">

        <a class="navbar-brand pr-5" style="border-right: 1px solid #efefef; " href="{% url 'posts:feed' %}">
            <img src="{% static 'img/instagram.png' %}" height="45" class="d-inline-block align-top"/>
        </a>

        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item">
                    <a href="{% url 'users:detail' request.user.username %}">
                        {% if request.user.profile.picture %}
                            <img src="{{request.user.profile.picture.url}}" 
                                class="rounded-circle" height="50">
                        {% else %}
                            <img src="{% static 'img/default-profile.png' %}" height="35"
                                class="d-inline-block align-top rounded-circle"/>
                        {% endif %}
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href="{% url 'posts:create_post' %}">
                        <i class="fas fa-plus"></i>
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    
                    <a href="{% url 'users:logout' %}">
                        <i class="fas fa-sign-out-alt"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/pagination.html
<nav>
    <ul class="pagination justify-content-end">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                Previous
            </a>
        </li>
        {% endif %}
        <li class="page-item">
            <a class="page-link" href="#">
                {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </a>
        </li>
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                Next
            </a>
        </li>
        {% endif %}
    </ul>
</nav>