red/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include(('posts.urls', 'posts'),  namespace='posts')),

    path('users/', include(('users.urls', 'users'), namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

users/urls.py
from django.urls import path
from users.views import (LoginView, LogoutView,
    UpdateProfileView, UserDetailView,
    SignupView)


urlpatterns = [
    path(
        route='login',
        view=LoginView.as_view(),
        name='login'
    ),
    path(
        route='logout',
        view=LogoutView.as_view(),
        name='logout'
    ),
    path(
        route='signup',
        view=SignupView.as_view(),
        name='signup'
    ),
    path(
        route='mw/update',
        view=UpdateProfileView.as_view(),
        name='user_update'
    ),
    path(
        route='profile/<str:username>',
        view=UserDetailView.as_view(),
        name='detail'
    ),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    """
    Profile model
    Proxy model that extends the baseuser model adding other columns
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    website = models.URLField(max_length=200, blank=True)
    facebook = models.CharField(max_length=60, blank=True)
    instagram = models.CharField(max_length=50, blank=True)
    biography = models.TextField(blank=True)
    phone_number = models.CharField(max_length=15, blank=True)
    picture = models.ImageField(upload_to='users/pictures',
        blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username

users/forms.py
from django import forms
from django.contrib.auth.models import User
from users.models import Profile

class SignupForm(forms.Form):
    username = forms.CharField(
        label=False,
        min_length=3,
        max_length=200,
        required=True,
        widget = forms.TextInput(
            attrs={
                'placeholder':'Nombre de usuario',
                'class': 'form-control',
                'required': True
            }
        )
    )
    password = forms.CharField(
        label=False,
        min_length=3,
        max_length=60,
        widget=forms.PasswordInput(
            attrs={
                'placeholder':'Contraseña',
                'class': 'form-control',
                'required': True
            }
        )
    )
    password_confirm = forms.CharField(
        label=False,
        min_length=3,
        max_length=50,
        widget=forms.PasswordInput(
            attrs={
                'placeholder':'Confirmar contraseña',
                'class': 'form-control',
                'required': True
            }
        )
    )
    first_name = forms.CharField(
        label=False,
        min_length=2, 
        max_length=50,
        widget=forms.TextInput(
            attrs={
                'placeholder':'Nombre(s)',
                'class': 'form-control',
                'required': True
            }
        )
    )
    last_name = forms.CharField(
        label=False,
        min_length=2,
        max_length=50,
        widget=forms.TextInput(
            attrs={
                'placeholder':'Apellido(s)',
                'class': 'form-control',
                'required': True
            }
        )
    )
    email = forms.CharField(
        label=False,
        min_length=6,
        max_length=70,
        widget=forms.EmailInput(
            attrs={
                'placeholder':'Correo',
                'class': 'form-control',
                'required': True
            }
        )
    )

    def clean_username(self):
        # Validates username to be unique
        username = self.cleaned_data.get('username')
        username_taken = User.objects.filter(username=username).exists()
        if username_taken:
            raise forms.ValidationError('Nombre de usario ya existente')
        return username

    def clean(self):
        # Last step in form verification
        data = super().clean()
        password = data.get('password')
        password_confirm = data.get('password_confirm')
        if password != password_confirm:
            raise forms.ValidationError('Las contraseñas no coinciden')
        return data

    def save(self):
        data = self.cleaned_data
        data.pop('password_confirm')
        user = User.objects.create_user(**data)
        profile = Profile(user=user)
        profile.save()

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import views
from .models import Profile
from .forms import SignupForm
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, FormView, UpdateView
from posts.models import Post

class LoginView(views.LoginView):
    template_name = 'users/login.html'

@login_required
def user_logout(request):
    logout(request)
    return redirect('users:login')

class LogoutView(views.LogoutView):
    template_name = ''

class SignupView(FormView):
    template_name = 'users/signup.html'
    form_class = SignupForm
    success_url = reverse_lazy('users:login')
    
    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

class UpdateProfileView(LoginRequiredMixin, UpdateView):
    template_name = 'users/update_profile.html'
    model = Profile
    fields = ['website', 'biography', 'phone_number', 'picture']
    
    def get_object(self):
        return self.request.user.profile

    def get_success_url(self):
        username = self.object.user.username
        return reverse('users:detail', kwargs={'username': username})

class UserDetailView(LoginRequiredMixin, DetailView):
    template_name = 'users/detail.html'
    slug_field = "username"
    slug_url_kwarg = 'username'
    queryset = User.objects.all()
    # Defines the context object name in the template
    context_object_name = 'user'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        context['posts'] = Post.objects.filter(user=user).order_by('-created')
        return context

templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css"crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
</head>
<body class="h-100">
    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5"id="auth-container">
                <img src="{% static 'img/instagram.png' %}" class="img-fluid rounded mx-auto d-block pb-4" style="max-width: 60%;">

                {% block container %}{% endblock%}
            </div>
        </div>
    </div>
</body>
</html>

templates/users/detail.html
{% extends "base.html" %}

{% block head_content %}
<title>@{{ user.username }}</title>
{% endblock %}

{% block container %}

    <div class="container mb-5" style="margin-top: 8em;">
        <div class="row">
            <div class="col-sm-4 d-flex justify-content-center">
                <img src="{{ user.profile.picture.url }}" alt="@{{ user.username}}" class="rounded-circle" width="150px" />
            </div>
            <div class="col-sm-8">
                <h2 style="font-weight: 100;">
                    {{ user.username }}
                    {% if request.user == user %}
                        <a
                            href="{% url "users:user_update" %}"
                            class="ml-5 btn btn-sm btn-outline-info"
                        >
                            Edit profile
                        </a>
                    {% else %}
                        <a
                            href=""
                            class="ml-5 btn btn-sm btn-primary"
                        >
                            Follow
                        </a>
                    {% endif %}
                </h2>
                <div class="row mt-2" style="font-size: 1.2em">
                    <div class="col-sm-4">
                        <b>{{ user.profile.posts_count }}785</b> posts
                    </div>
                    <div class="col-sm-4">
                        <b>{{ user.profile.followers }}1,401</b> followers
                    </div>
                    <div class="col-sm-4">
                        <b>{{ user.profile.following }}491</b> following
                    </div>
                </div>
                <div class="row mt-4">
                    <div class="col-sm-12">
                        <p>{{ user.profile.biography }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <hr>

    <div class="container" id="user-posts">
        <div class="row mt-3">
            {% for post in posts %}
            <div class="col-sm-4 pt-5 pb-5 pr-5 pl-5 d-flex justify-content-center align-items-center">
                <a href="" class="border">
                    <img src="{{ post.picture.url }}" alt="{{ post.title }}" class="img-fluid"/>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/users/login.html
{% extends "users/base.html"%}
{% block head_content %}
<title>login</title>
{% endblock %}
{% block container %}
    {% if form.errors %}
        <p class="alert alert-danger">Datos de cuenta incorrectos</p>
    {% endif %}
    <form action="{% url 'users:login' %}" method="post">
        <!-- csrf token for validate this form to submit to the endpoint -->
        {% csrf_token %}
        <div class="form-group">
            <input type="text" name="username" class="form-control"
            placeholder="Usuario" required='true'>
        </div>
        <div class="form-group">
            <input type="password" name="password" class="form-control"
                placeholder="Contraseña" required='true'>
        </div>
        <button class="btn btn-primary btn-block mt-5" type="submit">Login</button>
    </form>
    <p class="mt-4">Aun no tienes una cuenta? <a href="{% url 'users:signup' %}">Registrate aquí</a></p>
{% endblock%}

templates/users/signup.html
{% extends 'users/base.html' %}
{% block head_content %}
<title>Signup</title>
{% endblock %}

{% block container %}
    {% if error %}
        <p class="alert alert-danger">{{error}}</p>
    {% endif %}
    <h1>Sign up</h1>
    <form action="{% url 'users:signup' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary btn-block mt-5" type="submit">Signup</button>
    </form>
{% endblock %}

templates/users/update_profile.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
<title>@{{ request.user.username }}</title>
{% endblock %}

{% block container %}

  <divclass="container">

    <div class="row justify-content-md-center">
      <div class="col-6 p-4"id="profile-box">

        <form action="{% url 'users:user_update' %}" method="POST" enctype="multipart/form-data">
          {% csrf_token %}

          <div class='media'>
                {%if profile.picture %}
                    <img src="{{ profile.picture.url }}" class="rounded-circle" height="50">
                {% else %}
                    <img src="{% static 'img/default-profile.png' %}" class="rounded-circle" height="50"/>
                {% endif %}

                
                <div class="media-body">
                    <h5 class="ml-4">@{{ user.username }} | {{user.get_full_name}}</h5>
                    <p class="ml-4"><input type="file" name="picture" required="true"></p>
                </div>
            </div>

            {% for error in form.picture.errors %}
                <div class="alert alert-danger">
                    <b>Picture: </b>{{error}}
                </div> 
            {% endfor %}

          <hr><br>

          <div class="form-group">
            <label>Website</label>
            <input
                class="form-control"
                name="website"
                type="url"
                placeholder="Website"
                value="{% if form.errors %}
                    {{ form.website.value }}
                {% else %} 
                    {{ profile.website }}
                {%endif%}"
            />
            <div class="invalid-feedback">
                {% for error in form.website.errors%}
                    {{error}}
                {% endfor %}
            </div>
          </div>

          <div class="form-group">
            <label>Biography</label>
            <textarea class="form-control {% if form.biography.errors %}is-invalid{% endif %}" name="biography"
            >{% if form.errors %}{{ form.biography.value }}{% else %}{{ profile.biography }}{% endif %}</textarea>
            <div class="invalid-feedback">
                {% for error in form.biography.errors%}
                    {{error}}
                {% endfor %}
            </div>
          </div>

          <div class="form-group">
            <label>Phone number</label>
            <input
                class="form-control {% if form.phone_number.errors %}is-invalid{% endif %}"
                name="phone_number"
                type="text"
                placeholder="Phone number"
                value="{% if form.errors %}{{form.phone_number.value}}{% else %}{{ profile.phone_number }}{% endif %} "/>
            <div class="invalid-feedback">
                {% for error in form.phone_number.errors%}
                    {{error}}
                {% endfor %}
            </div>
          </div>

          <button class="btn btn-primary btn-block mt-5" type="submit">Actualizar</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}